export enum ConfigEnum {
    DATABASE_HOST = 'DATABASE_HOST',
    DATABASE_PORT = 'DATABASE_PORT',
    DATABASE_USER = 'DATABASE_USER',
    DATABASE_PASSWORD = 'DATABASE_PASSWORD',
    DATABASE_NAME = 'DATABASE_NAME',
}